version: '3.8'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local

services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - frontend
      - backend
  app:
    build: ./.docker/php-fpm
    container_name: app
    volumes:
      - ./:/var/www/html
    networks:
      - backend
  # db:
  #   image: mysql:5.7
  #   command:
  #     - --sql-mode=NO_ENGINE_SUBSTITUTION
  #   container_name: db
  #   ports:
  #     - 5000:3306
  #   environment:
  #     - MYSQL_DATABASE=cake-blog-tutorial
  #     - MYSQL_USER=mysql
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_ROOT_PASSWORD=password
  #   volumes:
  #     - ./.docker/mysql/etc-mysql.cnf:/etc/mysql/conf.d/etc-mysql.cnf
  #     - ./.docker/mysql/init:/docker-entrypoint-initdb.d
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - backend
  db:
    image: postgres:11.7
    container_name: db
    ports:
      - 5000:5432
    volumes:
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    networks:
      - backend
